### PR TITLE
pylint_check - follow PEP8 and Pylint

### PR DESCRIPTION
**Pull request by carlostse**
## Proposed Changes

Please describe the big picture of your changes here to communicate to
the Pika team why we should accept this pull request. If it fixes a bug
or resolves a feature request, be sure to link to that issue.

A pull request that doesn't explain **why** the change was made has a
much lower chance of being accepted.

If English isn't your first language, don't worry about it and try to
communicate the problem you are trying to solve to the best of your
abilities.  As long as we can understand the intent, it's all good.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation (correction or otherwise)
- [x] Cosmetics (whitespace, appearance)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after
creating the PR. If you're unsure about any of them, don't hesitate to
ask on the
[`pika-python`](https://groups.google.com/forum/#!forum/pika-python)
mailing list. We're here to help! This is simply a reminder of what we
are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further Comments

```
----------------------------------------------------------------------------------
TOTAL                                             6659   2336   1501    165    66%
----------------------------------------------------------------------
Ran 1178 tests in 57.666s

OK (SKIP=61)
```

### CODE REVIEW

**Comment by carlostse** [comment]
Sure, will remove those do not follow `yapf` format.

Regarding removal of `elif` and `else` because they are after `raise`, the code after `raise` won't be executed, so there are no need to use `else`

**Comment by carlostse** [comment]
@lukebakken Hey, just double checked, I haven't changed anything related to Python docs. The changes are just
1. removing unused import
2. align params in next line
3. ensure 2 space between # and program code
4. remove unnecessary `else` or `elif `
Thanks.

**Comment by michaelklishin** [comment]
@lukebakken any more changes you'd like to see in this PR?

**Comment by carlostse** [comment]
Thanks for merging

**Pull request merged**
