### PR TITLE
Long running publisher example

### PR DESCRIPTION
**Pull request by karls**
## Proposed Changes

Off the back of [the discussion](https://github.com/pika/pika/discussions/1382), here is a PR for an example of how to implement a long-running publisher and make use of the `BlockingConnection.process_data_events` method. I have updated the docstring for that method as well to clarify why this method should be used in this particular context.

## Types of Changes

- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by Zerpet — DISMISSED** [review]
This looks good to me :heavy_check_mark: One thing: the formatter `yapf` adds a few empty lines in the example. Can you incorporate those to the PR?

**Comment by karls** [comment]
> This looks good to me ✔️ One thing: the formatter `yapf` adds a few empty lines in the example. Can you incorporate those to the PR?

Cheers @Zerpet. I've re-formatted the example. From the commit logs in the repo it looks like at least one example has been formatted using `black`, instead of `yapf`. Is there a preference? FWIW both seem to do the same thing for the long-running publisher example, so in this case it doesn't matter much.

**Comment by Zerpet** [comment]
We prefer `yapf` with `google` style formatting. If two different formatters yield the same result, that would work too :slightly_smiling_face:

**Review by Zerpet — APPROVED** [review]

**Comment by Zerpet** [comment]
Looks like I can't click the merge button, we'll have to wait for @lukebakken :smile:

**Comment by Zerpet** [comment]
Thank you!

**Comment by karls** [comment]
Cheers @Zerpet and @lukebakken!

**Pull request merged**
