### PR TITLE
Fixed SSL import and removed no_ack=True in favor of explicit AMQP me…

### PR DESCRIPTION
**Pull request by skftn**
Addresses [this issue](https://github.com/pika/pika/issues/617) and removes `no_ack=True` to provide an example that is more Twisted-like.

It provides a better base for creating an asynchronous task based consumer with a pre-defined queue limit.

### CODE REVIEW

**Comment by vitaly-krugl** [comment]
@skftn: thanks for your contribution. Would you mind contributing some basic acceptance tests for Twisted connection? See https://github.com/pika/pika/blob/master/tests/acceptance/blocking_adapter_test.py as an example. Even just a handful of tests (e.g., connect, create channel, publish, get, consume) would be great. There aren't any tests at all for Twisted right now. Many thanks in advance!

**Comment by skftn** [comment]
@vitaly-krugl: Which files would need to be tested? I don't have any experience in writing tests for Twisted (or unittests in general). I can give it a try however.

**Comment by vitaly-krugl** [comment]
@skftn: I was thinking about acceptance tests for twisted adapters, rather than unit tests, just to get started. The project uses the python [unittest](https://docs.python.org/2/library/unittest.html) framework for all its tests - both unit and acceptance. Each test is a targeted basic usage workflow: e.g.,

1. method `test_twisted_connect_and_close`: initiate the connection sequence

Here is an example of a basic test script from [python unittest framework](https://docs.python.org/2/library/unittest.html); the test method names need to begin with "test_" to be recognized by the framework; you can have helper/private methods with names that don't begin with "test_"; it's desirable to use test method names that are descriptive of what's being tested (long names are okay in these tests).
```
import unittest

class TestStringMethods(unittest.TestCase):

  def test_upper(self):
      self.assertEqual('foo'.upper(), 'FOO')

  def test_isupper(self):
      self.assertTrue('FOO'.isupper())
      self.assertFalse('Foo'.isupper())

  def test_split(self):
      s = 'hello world'
      self.assertEqual(s.split(), ['hello', 'world'])
      # check that s.split fails when the separator is not a string
      with self.assertRaises(TypeError):
          s.split(2)

if __name__ == '__main__':
    unittest.main()
```

Definitely use unittest's specialized `self.assert*` methods rather than python's builtin `assert`. Unittest's specialized assertion methods output a bunch of useful info when assertions fail.

There is a lot of flexibility for structuring these tests: you can have a dedicated test class for each test method (as in https://github.com/pika/pika/blob/master/tests/acceptance/blocking_adapter_test.py) or multiple test methods per test class (as in the above example). It's up to you.

https://github.com/pika/pika/blob/master/tests/acceptance/blocking_adapter_test.py is an example of an acceptance test suite for the pika blocking adapter. Note the use of `self.addCleanup` immediately after creation of resources to schedule their destruction and the use of uuid to avoid collisions, especially when tests are executed in parallel.

**Comment by vitaly-krugl** [comment]
@skftn: issue #616 is tracking acceptance tests for the pika Twisted adapter

**Pull request merged**
