### PR TITLE
PEP-343 for blocking connection

### PR DESCRIPTION
**Pull request by reddec**
PEP-343 for BlockingConnection
[Original discussion](https://github.com/pika/pika/pull/627)

### CODE REVIEW

**Comment by vitaly-krugl** [comment]
Looks good to me, thanks!

**Comment by reddec** [comment]
Thank for you help!

**Comment by gmr** [comment]
Thanks for the contribution!

**Comment by gmr** [comment]
No -- think we need another pre-release or should we just let 0.10.0 out?

**Comment by vitaly-krugl** [comment]
I am concerned about #637 - I think @shinji-s might have something there with the EINTR issue on Ubuntu. If it's true, it would be good to get #637 into the release. I gave him an idea on how to write the EINTR test, so I am hoping this will happen soon.

**Pull request merged**
