### PR TITLE
Fix divide-by-zero error during backpressure calculation.

### PR DESCRIPTION
**Pull request by vitaly-krugl**
Fixes issue #728
Fixed update of bytes_sent in Connection._send_message (issue #728)

### CODE REVIEW

**Comment by vitaly-krugl** [comment]
CC @gmr: Ready for review

**Comment by gmr** [comment]
Are you sure this is the right fix? What about
https://github.com/vitaly-krugl/pika/blob/issue728-backpressure-divide-by-zero/pika/connection.py#L2120

Won't this PR count the # of bytes sent to be 2x what they are?

**Comment by vitaly-krugl** [comment]
@grm: No, `_send_frame` and `_send_message` are two distinct, non-overlapping code paths presently in pika; reference https://github.com/vitaly-krugl/pika/blob/issue728-backpressure-divide-by-zero/pika/connection.py#L2136-L2139

```
        if content:
            self._send_message(channel_number, method, content)
        else:
            self._send_frame(frame.Method(channel_number, method))
```

> Won't this PR count the # of bytes sent to be 2x what they are?

**Comment by vitaly-krugl** [comment]
Rebased against 51fd186f1fabe0da8582609d266df1e28e57e3f4

**Comment by mattcaldwell** [comment]
Any updates on this? Fix works for me.

**Pull request merged**
