### PR TITLE
Add the hostname of the server to client properties

### PR DESCRIPTION
**Pull request by markunsworth**
Passes the hostname of the client to the server when connecting. Useful for identifying connections when  multiple clients share the same username

### CODE REVIEW

**Comment by mffrench** [comment]
Hello @markunsworth,

interesting solution but what if you have several connections from same client (which could happen as pika connections are not really thread safe) ?

Currently still waiting this pull request or some other solutions : 
https://github.com/pika/pika/pull/571

Cheers,

Mathilde

**Comment by markunsworth** [comment]
We just wanted to know which connections were coming from which servers as the ip addresses shown in the `name` don't seem to match.

**Comment by vitaly-krugl** [comment]
@markunsworth: what if the user needs to pass fqdn?

**Comment by vitaly-krugl** [comment]
@markunsworth: please add tests to your PR.

**Comment by markunsworth** [comment]
@vitaly-krugl yes, it's limited for now, maybe pull request #571 by @mffrench is a better place to do this, we just need to agree on an approach

**Comment by gmr** [comment]
Closing for now due to lack of tests or agreed upon method of doing this. Thanks for the PR, please feel free to re-open if you add test coverage.

**Pull request closed without merging**
