### PR TITLE
Gevent stuff merged in

### PR DESCRIPTION
**Pull request by ccp-codex**

### CODE REVIEW

**Comment by ccp-codex** [comment]
My mistake. Too much egg-nog this season. :)

**Comment by lukebakken** [comment]
@ccp-codex - Hello! Are you working on finishing up #860!

**Comment by ccp-codex** [comment]
Hi @lukebakken I'm just reviewing the patch in my own fork for now but I will certainly commit back any changes if they will move the pull request forward. I'm pretty certain you won't want the custom stackless implementation I'll definitely be working on. ;)

**Comment by lukebakken** [comment]
It would be great to have help with #860 if you have time. Thanks!

**Pull request closed without merging**
