### PR TITLE
Restored BlockingConnection/BlockingChannel methods that were removed in initial SelectConnection wrapper implementation

### PR DESCRIPTION
**Pull request by vitaly-krugl**
Removed the new BlockingChannel.has_event and get_event.

Implemented majority of the balance of the BlockingConnection/BlockingChannel acceptance tests except `BlockingChannel.exchange_bind/exchange_unbind` and validation of `BasicProperties`

### CODE REVIEW

**Comment by gmr** [comment]
What should I make of the failed tests? Merge anyway?

**Comment by vitaly-krugl** [comment]
Gavin, please don't merge until tests are passing.

**Comment by vitaly-krugl** [comment]
I am going to rebase and squash shortly.

**Comment by vitaly-krugl** [comment]
Hi Gavin, I think that this PR is ready to merge. It's rebased against master and squashed, and all tests pass now.

**Pull request merged**
