### PR TITLE
Fixed minor function call overhead

### PR DESCRIPTION
**Pull request by AndreCimander**
## Proposed Changes

During some profiling I noticed a duplicated lambda call in the [call graph](https://04936760119988894920.googlegroups.com/attach/2a7cd6998e4b9/Screenshot_20200606_211952_normal_while.png?part=0.1&view=1), but I am not sure if this proposed change of a **while**-loop to a **do...while**-loop is side effect free as I don't have a full grasp of the internal polling flow, so don't hesitate to close this PR :)

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after
creating the PR. If you're unsure about any of them, don't hesitate to
ask on the
[`pika-python`](https://groups.google.com/forum/#!forum/pika-python)
mailing list. We're here to help! This is simply a reminder of what we
are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [x] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by AndreCimander** [comment]
Looking at the tests I would argue it has side effects :) 

Is there a special reason why the conditionals of `is_done` are wrapped into a function? Since it isn't reused I would argue moving those into the while loop will eliminate a few unnecessary function calls.

**Comment by AndreCimander** [comment]
I'll close this one as it starts to gather dust :)

**Comment by lukebakken** [comment]
@AndreCimander please be patient. We appreciate the time you've taken in submitting this pull request. The people who maintain Pika (mostly me at this point) do so in their free time. My main job is working on RabbitMQ and I spend time here when I can.

**Comment by AndreCimander** [comment]
@lukebakken no worries, this wasn't meant to put any pressure on anyone, sorry if I you felt that way :)

It's just a habit of mine to keep the open merge request count as low as possible, otherwise they seemingly start to multiply and projects become... unwieldy.

**Comment by michaelklishin** [comment]
The comment in `_flush_output` suggests that there is a reason:

``` py
# Conditions for terminating the processing loop:
        #   connection closed
        #         OR
        #   empty outbound buffer and no waiters
        #         OR
        #   empty outbound buffer and any waiter is ready
        is_done = (lambda:
                   self._closed_result.ready or
                   ((not self._impl._transport or
                     self._impl._get_write_buffer_size() == 0) and
                    (not waiters or any(ready() for ready in waiters))))
```

The condition is computed based on a number of factors and I don't think we can simply replace it with a `True` without behavior changes.

Thank you for taking the time to submit this 👍

**Pull request closed without merging**
