### PR TITLE
Added Python Example Code for Sender and Receiver Object Oriented with Design Pattern

### PR DESCRIPTION
**Pull request by soumilshah1995**
…d Code

## Proposed Changes

I have added two code sender and receiver code for RabbitMq with Design Pattern. Example shows
Passing Json Data from sender to receiver. the code is organized into classes. The Entire Architecture is loosely coupled and can be used with 3 lines of code as shown in example 

Please describe the big picture of your changes here to communicate to
the Pika team why we should accept this pull request. If it fixes a bug
or resolves a feature request, be sure to link to that issue.

A pull request that doesn't explain **why** the change was made has a
much lower chance of being accepted.

If English isn't your first language, don't worry about it and try to
communicate the problem you are trying to solve to the best of your
abilities.  As long as we can understand the intent, it's all good.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after
creating the PR. If you're unsure about any of them, don't hesitate to
ask on the
[`pika-python`](https://groups.google.com/forum/#!forum/pika-python)
mailing list. We're here to help! This is simply a reminder of what we
are going to look for before merging your code._

- [ ] I have read the `CONTRIBUTING.md` document
- [x ] All tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further Comments

If this is a relatively large or complex change, kick off the discussion
by explaining why you chose the solution you did and what alternatives
you considered, etc.

### CODE REVIEW

**Comment by soumilshah1995** [comment]
Hi  i am waiting for code review. can you review and push it to examples as it will help the community

**Comment by lukebakken** [comment]
Please be patient. Pika is maintained by people who do so, free of charge, on their own time.

**Comment by soumilshah1995** [comment]
> Please be patient. Pika is maintained by people who do so, free of charge, on their own time.

**Comment by soumilshah1995** [comment]
> Please be patient. Pika is maintained by people who do so, free of charge, on their own time.

Sure ! I am sorry for being a little Impatient.
Wanted to know do I need to reopen this as the status is showing closed. 
Just trying to understand the way code review works

**Comment by lukebakken** [comment]
@soumilshah1995 - _you_ mistakenly closed the issue, not me. You can see it above ^^^^

**Comment by lukebakken** [comment]
Thanks for taking the time to submit this. I don't believe it adds a useful example beyond what is available in the `examples/` directory of this repository. If you would like to provide the code in your own repository or gist and share it via the [`pika-python`](https://groups.google.com/forum/?pli=1#!forum/pika-python) or [`rabbitmq-users`](https://groups.google.com/forum/?pli=1#!forum/rabbitmq-users) mailing list that would be best.

**Pull request closed without merging**
