### PR TITLE
Fixed BlockingConnection handling of server-initiated Connection.Close as well as of sudden loss of connection with broker

### LINKED ISSUE #540: BlockingConnection fails to raise ConnectionClosed when socket connection is lost, later trips up on "Bad file descriptor"
Running on MacOS X. Same problem with 0.9.14 as well as master.

BlockingConnection fails to raise ConnectionClosed when socket connection is lost, and later trips up on `select.error: (9, 'Bad file descriptor')`. This problem happens in `BlockingConnection._on_connection_closed`:
 
0. When rabbitmq closes connection, it sends "Connection.Close"
1. `Connection._process_frame()` calls `connection._on_connection_closed(spec.Connection.Close)`, which is handled by `BlockingConnection._on_connection_closed`
2. `BlockingConnection._on_connection_closed` saves the reply_code and reply_text in self.closing , but then calls `self._adapter_disconnect()`, which resets self.closing to `0, 'Not specified'` in `Connection._init_connection_state()`
3. Subsequently, `BlockingConnection._on_connection_closed` fails to raise exceptions.ConnectionClosed because  `if self.closing[0] not in [0, 200]` evaluates to False after self.closing got reset to `0, 'Not specified'` above. So, ConnectionClosed is accidentally suppressed, and the caller trips up on `select.error: (9, 'Bad file descriptor')` instead

To reproduce

1. Run this code in python shell: 
 ```
from pika import BlockingConnection
connection = BlockingConnection()
channel = connection.channel()
channel.queue_declare("pika_error540")
for method, properties, body in channel.consume('pika_error540'):
    pass
```

2. Using RabbitMQ web GUI, click on the Connections tab and then click on the connection and click on the Force Close button to close the connection.

3. Returning to our code, we get this traceback. Note that ConnectionClosed exception is missing; instead, we get the misleading `select.error: (9, 'Bad file descriptor')` exception: 

 ```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vkruglikov/ossdev/pika/pika/adapters/blocking_connection.py", line 724, in consume
    exclusive)
  File "/Users/vkruglikov/ossdev/pika/pika/channel.py", line 221, in basic_consume
    {'consumer_tag': consumer_tag})])
  File "/Users/vkruglikov/ossdev/pika/pika/adapters/blocking_connection.py", line 1140, in _rpc
    self._wait_on_response(method_frame))
  File "/Users/vkruglikov/ossdev/pika/pika/adapters/blocking_connection.py", line 1161, in _send_method
    self.connection.process_data_events()
  File "/Users/vkruglikov/ossdev/pika/pika/adapters/blocking_connection.py", line 240, in process_data_events
    if self._handle_read():
  File "/Users/vkruglikov/ossdev/pika/pika/adapters/blocking_connection.py", line 347, in _handle_read
    if self._read_poller.ready():
  File "/Users/vkruglikov/ossdev/pika/pika/adapters/blocking_connection.py", line 43, in inner
    return f(*args, **kwargs)
  File "/Users/vkruglikov/ossdev/pika/pika/adapters/blocking_connection.py", line 89, in ready
    self.poll_timeout)
select.error: (9, 'Bad file descriptor')
```

### LINKED ISSUE #541: BlockingConnection.is_open evaluates to True when socket connection is dropped suddenly
Running on Mac OS X

To reproduce, 

1. run this code:

 ```
from pika import BlockingConnection
connection = BlockingConnection()
channel = connection.channel()
channel.queue_declare("pika_error541")
for method, properties, body in channel.consume('pika_error541'):
    pass
```

2. Find rabbitmq's pid (e.g., `ps aux | grep rabbitmq`) and kill the rabbitmq process to simulate sudden loss of connection with RabbitMQ.

3. This results in the following exception, which is reasonable:

 ```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vkruglikov/ossdev/pika/pika/adapters/blocking_connection.py", line 737, in consume
    self.connection.process_data_events()
  File "/Users/vkruglikov/ossdev/pika/pika/adapters/blocking_connection.py", line 240, in process_data_events
    if self._handle_read():
  File "/Users/vkruglikov/ossdev/pika/pika/adapters/blocking_connection.py", line 351, in _handle_read
    super(BlockingConnection, self)._handle_read()
  File "/Users/vkruglikov/ossdev/pika/pika/adapters/base_connection.py", line 348, in _handle_read
    return self._handle_disconnect()
  File "/Users/vkruglikov/ossdev/pika/pika/adapters/base_connection.py", line 248, in _handle_disconnect
    self._adapter_disconnect()
  File "/Users/vkruglikov/ossdev/pika/pika/adapters/blocking_connection.py", line 319, in _adapter_disconnect
    self._check_state_on_disconnect()
  File "/Users/vkruglikov/ossdev/pika/pika/adapters/blocking_connection.py", line 374, in _check_state_on_disconnect
    raise exceptions.ConnectionClosed()
pika.exceptions.ConnectionClosed
```
4. However, `connection.is_open` still evaluates to True after this, which is incorrect - it should evaluate to  False instead because self.socket has been closed and self.socket has been set to None in `BlockingConnection._adapter_disconnect()`, making the Connection object inconsistent; after the above ConnectionClosed traceback:
```
>>> connection.is_open
True  # this should be False instead because ConnectionClosed was raised, and the state of the connection needs to correctly reflect that, otherwise user code gets confused.
>>> 
```

### PR DESCRIPTION
**Pull request by vitaly-krugl**
Fixed #541 - Make sure connection state is properly reset when BlockingConnection._check_state_on_disconnect raises ConnectionClosed. This supplements the previously-merged PR #450 by getting the connection into consistent state.

Fixed #540 - fix handling of Connection.Close in BlockingConnection._on_connection_closed that was preventing ConnectionClosed from being raised.

Also, together with PR #533, this should address #412

### CODE REVIEW

**Comment by vitaly-krugl** [comment]
Very strange situation with coverall failure here: my test only added about 5 lines of code, so I don't see why it's unhappy.

**Comment by gmr** [comment]
Thanks for the PR, I'll take a look ASAP.

**Comment by vitaly-krugl** [comment]
Together with PR #532, this should address #412

**Comment by gmr** [comment]
LGTM, thanks

**Pull request merged**
