### PR TITLE
add thread lock for blocking connection, thread safe

### PR DESCRIPTION
**Pull request by zjj**
This is an attempt to address #892.

### CODE REVIEW

**Comment by zjj** [comment]
is the lock for _flush_output enough ???

**Comment by michaelklishin** [comment]
Thread safety is a property of an algorithm (a sequence of steps). You haven't mentioned what specific scenario you are trying to make safer, so we can't know whether locking in that one function is enough.

Locking around I/O reads should be done with care. The same can be said for writes but in practice most if not all clients do it and combined with heartbeats it works OK. It can have devastating effect on throughput, as demonstrated by recent .NET client changes (there were multiple ones, both for publishers and consumers, so I'm not linking to a specific one). Were any benchmarks conducted to compare the difference for the "no concurrent access" (only one thread) scenario, which is likely to be the most common one?

**Comment by zjj** [comment]
@michaelklishin  see issue #892

**Comment by vitaly-krugl** [comment]
@michaelklishin  - there are far too many other code paths in pika blocking connection that are not thread safe, so a one-off solution is lackluster. 

The inactivity_timeout feature in BlockingChannel.consume can be used to easily solve the problem in application code without adding a hack in pika.

**Comment by lukebakken** [comment]
@vitaly-krugl thank you for adding your input.

**Pull request closed without merging**
