### PR TITLE
pika.compat should be a module, not package

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes the issue raised here:

https://github.com/pika/pika/issues/945#issuecomment-366148312

### CODE REVIEW

**Comment by anton-ryzhov** [comment]
@vitaly-krugl because `distutils` installs only **packages** listed under `packages` keyword in `setup.py`. `compat.py` was a part of `pika` package, but `compat/__init__.py` is a new `pika.compat` package, different than just `pika`.
If you add new [sub]packages, you must list it in `setup.py`. Or use http://setuptools.readthedocs.io/en/latest/setuptools.html#using-find-packages

**Comment by vitaly-krugl** [comment]
> because distutils installs only packages listed under packages keyword

So, one option was to list `compat/__init__.py` in setup.py instead of turning it into `compat` module? Just curious.

**Comment by anton-ryzhov** [comment]
Yes, sure, like this:
```python
setuptools.setup(
    …
    packages=['pika', 'pika.adapters', 'pika.compat'],
    …
)
```
or even better (autodiscovery):
```python
from setuptools import find_packages

setuptools.setup(
    …
    packages=find_packages(exclude=['*.tests', '*.tests.*', 'tests.*', 'tests']),
    …
)
```

**Comment by lukebakken** [comment]
@vitaly-krugl apologies that I missed your question and thank you @anton-ryzhov for answering it.

**Comment by vitaly-krugl** [comment]
Thanks @anton-ryzhov!

@lukebakken - I like the `find_packages()` recommendation for auto-discovery. What do you think?

**Comment by lukebakken** [comment]
I doubt Pika will add packages in the future. The issue around `compat` was all my mistake in thinking it had to be a package.

**Pull request merged**
