### PR TITLE
Fix exchange type enum type

### PR DESCRIPTION
**Pull request by liortct**
Addressing  #1409 .
Fix `ExchangeType` enum type to str.

### CODE REVIEW

**Review by lukebakken — CHANGES_REQUESTED** [review]
Please see this comment, thanks - https://github.com/pika/pika/issues/1409#issuecomment-1366156190

**Comment by liortct** [comment]
> Please see this comment, thanks - [#1409 (comment)](https://github.com/pika/pika/issues/1409#issuecomment-1366156190)

You are right but `StrEnum` is new in Python 3.11.
I want this will work not only for Python 3.11 so I don't use `StrEnum` and simply did like [here](https://docs.python.org/3.10/library/enum.html#others) and inheritance from `str`.

**Comment by lukebakken** [comment]
Argh that's annoying.

Could you try to do an import, catch the `ImportError`, and fix things up? Otherwise at some point I'm going to forget that `StrEnum` is available and never update the code.

I'd rather do that than check the python version.

Thanks!

**Comment by liortct** [comment]
> Argh that's annoying.
> 
> Could you try to do an import, catch the `ImportError`, and fix things up? Otherwise at some point I'm going to forget that `StrEnum` is available and never update the code.
> 
> I'd rather do that than check the python version.
> 
> Thanks!

Fixed :)

**Review by lukebakken — APPROVED** [review]
Thanks!

**Comment by liortct** [comment]
> Thanks!

Can you merge this PR?

**Comment by lukebakken** [comment]
> Can you merge this PR?

Yes, I was waiting for the checks to finish.

**Pull request merged**
