### PR TITLE
Python 3.10 support

### PR DESCRIPTION
**Pull request by Anthchirp**
## Proposed Changes

Add support for Python 3.10.

## Types of Changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes issue #NNNN)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation (correction or otherwise)
- [ ] Cosmetics (whitespace, appearance)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after
creating the PR. If you're unsure about any of them, don't hesitate to
ask on the
[`pika-python`](https://groups.google.com/forum/#!forum/pika-python)
mailing list. We're here to help! This is simply a reminder of what we
are going to look for before merging your code._

- [x] I have read the `CONTRIBUTING.md` document
- [ ] All tests pass locally with my changes
- [x] I have added tests ~that prove my fix is effective or that my feature works~
- [x] I have added necessary documentation (if appropriate)

## Further Comments

Pika's testing framework, nose, will not run on Python 3.10. The last nose update was 2015, and it is very unlikely that there will be a Python 3.10 compatible release. Therefore pika tests won't run on Python 3.10.

In this PR I changed the test setup to run on nose2, which seems to sort of mostly work.
However, [`twisted_adapter_tests.py` uses `nose.twistedtools`](https://github.com/pika/pika/blob/55557c9172edb04256a5e49b7faf13078d5a0f66/tests/acceptance/twisted_adapter_tests.py#L18), which is not available in nose2. I don't use twisted, so I have no idea how to migrate this test.

### CODE REVIEW

**Comment by lukebakken** [comment]
Thanks, I'll check this out soon.

**Comment by gaby** [comment]
@lukebakken any updates on this? Support for Py3.10 is way overdue

**Comment by lukebakken** [comment]
> @lukebakken any updates on this? Support for Py3.10 is way overdue

No updates as I've been working on issues for paying RabbitMQ customers. Maybe I'll find time soon to get to this. In the meantime, someone could take initiative and set up the Linux and Windows builds on GH actions. These would be good references:

https://github.com/rabbitmq/rabbitmq-dotnet-client/tree/main/.github/workflows
https://github.com/rabbitmq/amqp091-go/tree/main/.github/workflows
https://github.com/cloudamqp/amqp-client.rb/tree/main/.github/workflows

**Comment by lukebakken** [comment]
Yep, that's why we install RabbitMQ manually on Windows build runners -

https://github.com/rabbitmq/rabbitmq-dotnet-client/tree/main/tools

**Comment by gaby** [comment]
@lukebakken Thanks for pointing to those files, unfortunately I have 0 experience doing development on Windows. I will try using a different amqp library

**Comment by lukebakken** [comment]
@gaby If all goes well I'm planning on releasing 1.2.1 with 3.10 support today.

**Comment by gaby** [comment]
Thank you!

**Comment by lukebakken** [comment]
@gaby version 1.2.1 is available via pypi. Thanks for your patience.

**Comment by gaby** [comment]
@lukebakken Thank you! 😁

**Pull request merged**
