### PR TITLE
use the socket type and proto field from addr info

### PR DESCRIPTION
**Pull request by lexdene**

### CODE REVIEW

**Comment by vitaly-krugl** [comment]
@lexdene, which specific problem is this addressing?

**Comment by lexdene** [comment]
@vitaly-krugl, I created this pr because I was confused with the hard code `sock_type` and `sock_proto` param inside `_create_tcp_connection_socket` function.

**Comment by lexdene** [comment]
@vitaly-krugl, I pushed new commits to get rid of the default arg values and add docstring.

**Comment by vitaly-krugl** [comment]
@lexdene - thank you!

**Pull request merged**
