### PR TITLE
exception shall be socket.error in _PollerBase

### PR DESCRIPTION
**Pull request by zjj**

### CODE REVIEW

**Comment by zjj** [comment]
@michaelklishin  some tests are not covered.

**Comment by lukebakken** [comment]
Hello!

Starting in Python 3.3, the exception raised is `OSError`. I will incorporate this fix into a new PR today. Thanks!

**Comment by michaelklishin** [comment]
It would help a lot if you explained what problem we are trying to solve here. How can it be reproduced?

**Comment by lukebakken** [comment]
`socket.error` was replaced by `OSError` in Python 3.3, but some instances of `socket.error` remain.

**Comment by zjj** [comment]
python2 socket.err
python3 either OSError or IOError works.

**Pull request closed without merging**
