### PR TITLE
blocking_adapter: only consider processable events

### LINKED ISSUE #753: Socket Error: 104 consuming messages with task that take a long time
As in #418 I have problem consuming messages with task that take a long time.
I am using git master setting heartbeat_interval=0.

My code is very similar to 
http://pika.readthedocs.io/en/0.10.0/examples/asynchronous_consumer_example.html
but my on_message method take some minutes to "consume" the message.

after some time consuming message I get:

```
INFO 2016-05-27 16:28:51,083 __main__ connect  101 : Connecting to localhost
INFO 2016-05-27 16:28:51,084 pika.adapters.base_connection _create_and_connect_to_socket  216 : Connecting to ::1:5672
INFO 2016-05-27 16:28:51,089 __main__ on_connection_open  117 : Connection opened
INFO 2016-05-27 16:28:51,089 __main__ add_on_connection_close_callback  126 : Adding connection close callback
INFO 2016-05-27 16:28:51,089 __main__ open_channel  169 : Creating a new channel
INFO 2016-05-27 16:28:51,092 __main__ on_channel_open  181 : Channel opened
INFO 2016-05-27 16:28:51,092 __main__ add_on_channel_close_callback  193 : Adding channel close callback
INFO 2016-05-27 16:28:51,092 __main__ start_consuming  223 : Issuing consumer related RPC commands
INFO 2016-05-27 16:28:51,092 __main__ add_on_cancel_callback  233 : Adding consumer cancellation callback
INFO 2016-05-27 16:28:51,102 __main__ on_message  263 : Received message # 1 from None
INFO 2016-05-27 16:43:45,104 __main__ run  72  : Done
INFO 2016-05-27 16:43:45,883 __main__ acknowledge_message  312 : Acknowledging message 1
ERROR 2016-05-27 16:43:45,884 pika.adapters.base_connection _handle_error  362 : Socket Error: 104
INFO 2016-05-27 16:43:45,884 pika.connection _on_terminate  1891: Disconnected from RabbitMQ at localhost:5672 (-1): error(104, 'Connection reset by peer')
WARNING 2016-05-27 16:43:45,885 __main__ on_channel_closed  209 : Channel 1 was closed: (-1) error(104, 'Connection reset by peer')
WARNING 2016-05-27 16:43:45,886 pika.connection close  1135: Suppressing close request on <SelectConnection CLOSED socket=None params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
WARNING 2016-05-27 16:43:45,887 __main__ on_connection_closed  144 : Connection closed, reopening in 5 seconds: (-1) error(104, 'Connection reset by peer')
INFO 2016-05-27 16:43:50,892 __main__ connect  101 : Connecting to localhost
```

On the log you can see function and line before meaage.
I have tried to execute my task in thread maintaining the amqp comunication in the main process with:

```
self._connection.ioloop.stop()
while (thread.isAlive()):
            #self._connection.ioloop.poll(write_only=True)
            #self._connection.ioloop.poll()                                                                                               
            time.sleep(3)
```

write_only=True was available in previous version
self._connection.ioloop.poll() create a recursion call with a lot of thread and problems
self._connection.ioloop.start()

So I don't have solution, I cannot consume messages and all is stalled.
Is possible we need a (background) poll to maintain socket and do not get new messages from queue?

### PR DESCRIPTION
**Pull request by lukebakken**
Includes and supercedes #803 

Does not resolve #753 (initially thought it might)

### CODE REVIEW

**Comment by vitaly-krugl** [comment]
I was able to reproduce the issue on OS X using @westphahl's code snippet from #803 to which I added some printfs to help grok the flow of events:

```python
import logging
import pika


class Consumer:

    def run(self, queue):
        self.connection = connection = pika.BlockingConnection()
        channel = connection.channel()

        channel.basic_qos(prefetch_count=1, all_channels=True)
        channel.queue_declare(queue=queue, durable=False,
                              exclusive=False, auto_delete=False)
        channel.basic_consume(self.on_message, queue)
        connection.add_timeout(1, self.on_timeout)
        try:
            channel.start_consuming()
        except KeyboardInterrupt:
            channel.stop_consuming()

    def on_timeout(self):
        print "ZZZ on_timeout called"
        self.connection.add_timeout(1, self.on_timeout)

    def on_message(self, channel, method, properties, body):
        print "ZZZ on_message called, starting connection.sleep(200)"
        self.connection.sleep(200)
        print "ZZZ calling basic_ack"
        channel.basic_ack(method.delivery_tag)
        print "ZZZ returned from basic_ack"


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    consumer = Consumer()
    consumer.run("foobar")
```

It fails about 200 seconds after publishing an event into the "foobar" queue:

```
INFO:pika.adapters.base_connection:Connecting to 127.0.0.1:5672
INFO:pika.adapters.blocking_connection:Created channel=1
ZZZ on_timeout called
ZZZ on_timeout called
ZZZ on_timeout called
ZZZ on_timeout called
ZZZ on_timeout called
ZZZ on_timeout called
ZZZ on_timeout called
ZZZ on_timeout called
ZZZ on_timeout called
ZZZ on_timeout called
ZZZ on_timeout called
ZZZ on_timeout called
ZZZ on_timeout called
ZZZ on_timeout called
ZZZ on_message called, starting connection.sleep(200)
ZZZ calling basic_ack
ZZZ returned from basic_ack
ZZZ on_timeout called
ERROR:pika.adapters.base_connection:Fatal Socket Error: error(32, 'Broken pipe')
WARNING:pika.adapters.base_connection:Socket closed when connection was open
WARNING:pika.connection:Disconnected from RabbitMQ at localhost:5672 (0): Not specified
CRITICAL:pika.adapters.blocking_connection:Connection close detected
Traceback (most recent call last):
  File "pika_nonactionable_events.py", line 36, in <module>
    consumer.run("foobar")
  File "pika_nonactionable_events.py", line 17, in run
    channel.start_consuming()
  File "/Users/vkruglikov/Library/Python/2.7/lib/python/site-packages/pika/adapters/blocking_connection.py", line 1681, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/Users/vkruglikov/Library/Python/2.7/lib/python/site-packages/pika/adapters/blocking_connection.py", line 647, in process_data_events
    self._flush_output(common_terminator)
  File "/Users/vkruglikov/Library/Python/2.7/lib/python/site-packages/pika/adapters/blocking_connection.py", line 426, in _flush_output
    raise exceptions.ConnectionClosed()
pika.exceptions.ConnectionClosed

```

**Comment by westphahl** [comment]
I was again able to reproduce the problem (after waiting long enough). The issue  is more obvious when enabling debug logging. Then there is a flood of messages like:

```
DEBUG:pika.adapters.select_connection:add_timeout: added timeout 1106198814716520823; deadline=0.001033782958984375 at 1501048203.384139
DEBUG:pika.adapters.select_connection:remove_timeout: removed 1106198814716520823
DEBUG:pika.adapters.select_connection:add_timeout: added timeout 7612051997220596087; deadline=0.0009546279907226562 at 1501048203.3841395
DEBUG:pika.adapters.select_connection:remove_timeout: removed 7612051997220596087
DEBUG:pika.adapters.select_connection:add_timeout: added timeout 8739932674260658551; deadline=0.0008752346038818359 at 1501048203.3841393
```

This PR fixes the issue for me :+1:

**Comment by lukebakken** [comment]
@vitaly-krugl does this PR resolve the issue for you as well?

**Comment by michaelklishin** [comment]
@westphahl thank you for confirming!

**Pull request merged**
